[package]
name = "distancias"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
rand = "0.8.5"
reqwest = "0.12.4"
serde_json = "1.0.117"
tokio = { version="1", features=["full"] }
tokio-macros = "2.3.0"
